# Generated by Django 3.0.5 on 2020-04-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque_liens_img_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(blank=True, max_length=100, null=True)),
                ('carousel', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('devise', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options_organisee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_option', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lien_img', models.CharField(blank=True, max_length=100, null=True)),
                ('my_school_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.MySchoolSchool')),
            ],
        ),
        migrations.CreateModel(
            name='Activites_scolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lien_img', models.CharField(blank=True, max_length=100, null=True)),
                ('my_school_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.MySchoolSchool')),
            ],
        ),
        migrations.AddField(
            model_name='myschoolschool',
            name='banque_liens_img_school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Banque_liens_img_School'),
        ),
        migrations.AddField(
            model_name='myschoolschool',
            name='details_school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.Details_school'),
        ),
    ]
