# Generated by Django 3.0.3 on 2020-03-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20200328_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myschoolapp',
            name='myschoolprofil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MySchoolProfil_set', to='Backend.MySchoolProfil'),
        ),
    ]
