# Generated by Django 3.0.5 on 2020-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20200428_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_school',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details_school',
            name='devise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details_school',
            name='historique',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
