# Generated by Django 3.0.3 on 2020-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20200328_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myschoolprofil',
            name='myschool',
        ),
        migrations.AddField(
            model_name='myschoolprofil',
            name='myschool',
            field=models.ManyToManyField(blank=True, null=True, related_name='MySchoolUser_set', to='Backend.MySchoolUser'),
        ),
    ]
