# Generated by Django 3.0.5 on 2020-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20200502_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_school',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
