# Generated by Django 3.0.3 on 2020-03-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20200330_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myschoolprofil',
            name='myschool',
        ),
        migrations.CreateModel(
            name='RelationUserProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MySchoolUser_set', to='Backend.MySchoolProfil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MySchoolProfil_set', to='Backend.MySchoolUser')),
            ],
        ),
    ]
