# Generated by Django 3.0.5 on 2020-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_details_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_school',
            name='impact_sociaux_eco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details_school',
            name='situation_geographique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
