# Generated by Django 3.0.5 on 2020-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20200502_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options_organisee',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
