# Generated by Django 3.0.3 on 2020-04-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20200331_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchoolSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='relationuserprofil',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myschooluserSet', to='Backend.MySchoolUser'),
        ),
        migrations.CreateModel(
            name='RelationSchoolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MySchoolSchool_set', to='Backend.MySchoolSchool')),
                ('schooluser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MySchoolSchool_set', to='Backend.MySchoolUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
