# Generated by Django 3.0.3 on 2020-04-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20200402_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationuserprofil',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myschoolschoolSet', to='Backend.MySchoolSchool'),
        ),
        migrations.AlterField(
            model_name='relationschooluser',
            name='schooluser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myschoolschoolSet_r', to='Backend.MySchoolUser'),
        ),
    ]
